OC_projet_8_nutella/urls.py
from django.urls import path, include
from django.contrib import admin

from home import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('legales_notices/', views.legales_notices, name='legales_notices'),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('products/', include('products.urls')),
    path('favorites/', include('favorites.urls')),
    path(
        'autocomplete/', include('autocomplete.urls', namespace="autocomplete")
    ),
]

autocomplete/urls.py
from django.urls import path

from . import views

app_name = "autocomplete"

urlpatterns = [path("", views.complete, name="complete")]

favorites/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('save/', views.favorite_save, name='favorite_save'),
    path('list/', views.favorite_list, name='favorite_list'),
]

users/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('account/', views.accountlog, name='accountlog'),
]

favorites/models.py
from django.db import models
from django.conf import settings

from users.models import User
from products.models import Product


class Favorite(models.Model):
    """ Cette class sert à avoir une table de favoris pour enregistrer
        les utilisateurs, les produits recherchés et les substitues trouvés
    """
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="favorites"
    )
    product = models.ForeignKey(
        "products.Product", on_delete=models.CASCADE, related_name="favorites_as_product"
    )
    substitute = models.ForeignKey(
        "products.Product", on_delete=models.CASCADE, related_name="favorites_as_substitute"
    )
    
    def __str__(self):
        return self.substitute.product_name

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from users.models import User


class ConnexionForm(forms.Form):
    """ Cette class sert à pouvoir utiliser l'username et le password pour se connecter """

    username = forms.CharField(label="Nom d'utilisateur", max_length=20)
    password = forms.CharField(label="Mot de passe", widget=forms.PasswordInput, min_length=6, max_length=16)

class SearchForm(forms.Form):
    """ Cette class sert à montré le champd de recherche sur le site pour trouvé le produit demandé """
    
    product = forms.CharField(
        label="", 
        max_length=100, 
        widget=forms.TextInput(attrs={'placeholder': "Champs de recherche"})
)

class SignupForm(UserCreationForm):
    """ Cette class sert à enregistrer username, ces 2 password et l'email """

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("username", "email")

favorites/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from home.forms import SearchForm
from products.models import Product, Category
from favorites.models import Favorite


@login_required()
def favorite_save(request):
    """Sert à sauvegarder les produits enregistrées par les utilisateurs"""
    if request.method == "POST":
        substitute_code = int(request.POST.get("substitute-code"))
        product_code = int(request.POST.get("product-code"))
        substitute = Product.objects.get(code=substitute_code)
        product = Product.objects.get(code=product_code)

        if substitute and product:
            Favorite.objects.get_or_create(user=request.user, product=product, substitute=substitute)

        return redirect("product_info", substitute_code)

    return redirect("home")

@login_required()
def favorite_list(request):
    """Sert à afficher les produits sauvegarder par les utilisateurs"""
    form = SearchForm()
    favorites = Favorite.objects.filter(user=request.user)
    return render(request, "favorites.html", {
        "favorites":favorites, "form": form,
    })

home/views.py
from django.shortcuts import render
from django.contrib.auth import login

from products.models import Product, Category
from .forms import SearchForm


def home(request):
    """ Cette méthode sert à utiliser le formulaire pour la page home.html """
    form = SearchForm()
    return render(request, 'home.html', {
        "form":form
    })

def legales_notices(request):
    return render(request, "legales_notices.html")

home/templates/account.html
{% extends 'base.html' %}
{% load static %}

{% block header %}

<header class="product-head">
    <img src="{% static 'img/image-favoris.jpg' %}" alt="image de fond pour account" class="product-image">

    {% block header_content %}

    <h2 class="product-account-title">Ahoy</h2> 
    <h2 class="product-head-title">{{ user.username }}!</h2>

    {% endblock %}
    
</header> 
    
{% endblock %}

{% block content %}

    <p class="account-email">Votre adresse email: {{ user.email }}</p>
    
{% endblock %}

home/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Font Awesome Icons -->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="{% static 'vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">
    <link href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" rel="stylesheet">


    <!-- Theme CSS - Includes Bootstrap -->
    <link href="{% static 'css/creative.min.css' %}" rel="stylesheet">

    <script src="https://kit.fontawesome.com/d56e60b09e.js" crossorigin="anonymous"></script>

    <title>{% block title %}Pojet-10{% endblock %}</title>

</head>

<body id="page-top" class="d-flex flex-column">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="{% url 'home' %}">
                <img src="{% static 'img/logo_pur_beurre_favicon.png' %}" alt="icone pur beurre"> 
                Pur Beurre
            </a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto my-2 my-lg-0">
                    <li class="nav-item">
                        <div class="container">
                            <form action="{% url 'research' %}" method="get" class="header-form">
                                {% csrf_token %}
                                <input type="text" id="product-input" name="product" class="form-control product-input">
                            </form>
                        </div>
                    </li>
                    <li class="nav-item">
                    {% if user.is_authenticated %}
                        <a class="nav-link js-scroll-trigger" href="{% url 'accountlog' %}"><i class="fas fa-user"></i></a>
                    {% else %}
                        <a class="nav-link js-scroll-trigger" id="button-login" href="{% url 'login' %}"><i class="fas fa-sign-in-alt"></i></a>
                    {% endif %}
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="{% url 'favorite_list' %}"><i class="fas fa-carrot"></i></a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                    {% if user.is_authenticated %}
                        <a class="nav-link js-scroll-trigger" id="button-logout" href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i></a>
                    {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% block header %}
      <!-- Masthead -->
        <header class="masthead flex-shrink-0">
            {% block header_content %}
            {% endblock %}
        </header>
    {% endblock %}

    <main class="flex-grow-1 flex-shrink-0">
        {% block content %}
        {% endblock %}
    </main>

    <!-- Footer -->
    <footer class="bg-light py-5 flex-shrink-0">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <a class="nav-link col-sm-2" href="{% url 'legales_notices' %}">
                    <button type="button" class="btn btn-link">Mentions légales</button>
                </a>
                <div class="small text-center text-muted col-sm-9">Copyright &copy; 2020 - Jérémy GUYOT</div>
                <a class="nav-link col-sm-1" href="{% url 'home' %}#contact">
                    <button type="button" class="btn btn-link">Contact</button>
                </a>
            </div>
            
        </div>
    </footer>

    
    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <script src="{% static 'vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

    <!-- jquery-ui -->
    <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js" integrity="sha256-eGE6blurk5sHj+rmkfsGYeKyZx3M4bG+ZlFyA7Kns7E=" crossorigin="anonymous"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'js/creative.min.js' %}"></script>
    <script>
        const autocomplete_url = "{% url 'autocomplete:complete' %}";
    </script>
    {{ block.super }}
    <script src="{% static 'js/autocomplete.js' %}"></script>
    
</body>

</html>

home/templates/favorites.html
{% extends 'base.html' %}
{% load static %}


{% block header %}

<header class="product-head-favorite header-container-favorite">
    <img src="{% static 'img/image-favoris.jpg' %}" alt="image de fond pour favoris" class="image-fond-favorite">
</header> 

{% endblock %}

{% block content %}

<div class="product-result container">
    <p class="row"><h3>Vois-ci le résultat de vos favoris:</h3></p>
    <div class="row">
        {% for favorite in favorites %}
        <div class="col-md-4 result">
            <div class="result-image-nutriscore">
                <img src="{{ favorite.substitute.image_url }}" width="100" height="100" class="result-image">
                <div class="result-nutriscore result-nutriscore-{{ favorite.substitute.nutrition_grade_fr }}">{{ favorite.substitute.nutrition_grade_fr }}</div>
            </div>
            <p><a class="result-name" href="{% url 'product_info' favorite.substitute.code %}">{{ favorite.substitute.product_name }}</a></p>
        </div>
        {% empty %}
        <p class="col-12">Aucun favoris enregistrées</p>
        {% endfor %}

    </div>
</div>

{% endblock %}

home/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block header %}

<header class="masthead">
    {% block header_content %}

    <div class="header-container"> 
    <h1>Du gras oui, mais de qualité!</h1>
    <hr>
    <h2>Trouvez un produit de substitution pour ceux que vous consommez tous les jours.</h2>

    <form action="{% url 'research' %}" method="get" class="header-form">
        {% csrf_token %}
        <input type="text" id="product-input" name="product" class="form-control product-input">
        <p><button type="submit">Rechercher</button></p>
    </form>
    

    {% if envoi %}
        <p>Vois-ci votre résultat: </p>
    {% endif %}
    </div>

    {% endblock %}
</header>

{% endblock %}


{% block content %}

    <!-- About Section -->
    <section class="page-section bg-primary" id="about">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8 text-center">
                    <h2 class="text-white mt-0">Colette et Remy</h2>
                    <hr class="divider light my-4">
                    <p class="text-white-50 mb-4">Colette Tatou : "Nous aimons tous manger, surtout en France ! Personnellement, une baguette fraîche, du bon fromage de chèvre et un bon vin rouge me suffisent amplement. Comme tout le monde, je fais mes courses au supermarché. Mais petit à petit je me suis rendue compte, surtout lorsque nous avons ouvert le restaurant, que je pouvais remplacer les produits aseptisés que j'avais l'habitude d'acheter par de bons produits du terroir Et souvent pour le même prix !"
                        <hr>Remy : "Pour ma part je me rendais déjà dans bien des magasins car j'aime beaucoup me balader, surtout dans les caves et les cuisines. Je connaissais par coeur le contenu des boutiques bio (dont je raffole) ainsi que les ingrédients de tous les aliments vendus. Lorsque Colette m'a demandé si elle pouvait remplacer son Nutella matinal par un aliment plus sain, je savais tout de suite où le trouver. L'idée de Pur Beurre était née !"
                    </p>
                    <img src="{% static 'img/colette_tatou_full.png' %}" alt="image de Colette">
                    <img src="{% static 'img/remy.jpg' %}" alt="image de Remy">
                </div>
            </div>
        </div>
    </section>

    <!-- Contact Section -->
    <section class="page-section" id="contact">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8 text-center">
                    <h2 class="mt-0">Contactez-nous !</h2>
                    <hr class="divider my-4">
                    <p class="text-muted mb-5">Je suis là pour vous, aux besoins !</p>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
                    <i class="fas fa-phone fa-3x mb-3 text-muted"></i>
                    <div>(+33) 07-89-12-63-45</div>
                </div>
                <div class="col-lg-4 mr-auto text-center">
                    <i class="fas fa-envelope fa-3x mb-3 text-muted"></i>
                    <!-- Make sure to change the email address in anchor text AND the link below! -->
                    <a class="d-block" href="mailto:jeremyguyot@gmail.com">jeremyguyot@gmail.com</a>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

home/templates/legales_notices.html
{% extends "base.html" %}
{% load static %}
{% block header %}
<div class="container-fluid">

    <div class="row">
        <div class="col-0 col-md-3"></div>
        <div class="col-12 col-md-6 text-center">
            <h2 class="mt-5 p-2 search">Mentions légales</h2>
        </div>
        <div class="col-0 col-md-3"></div>
    </div>

</div>
{% endblock %}

{% block content %}
<section class="container-fluid">

    <div class="row">
        <div class="col-0 col-md-3"></div>
        <div class="col-12 col-md-6 text-center">
            <h3 class="legale"><a href="https://unsplash.com/@olenka_kotyk">Olenka Kotyk</a> - Pour les images de fonds</h3>
            <h3 class="legale"><a href="https://unsplash.com/@kawin">Kawin Harasai</a> - Pour les images de fonds</h3>
            <h3 class="legale"><a href="https://fontawesome.com/icons?d=gallery">Font Awesome</a> - Pour les icônes</h3>
            <h3 class="legale"><a href="https://world.openfoodfacts.org/nutriscore">Open Food Facts</a> - Pour les logos 'nutri-score'</h3>

            <h2 class="pt-4 legale">Ce site à pue être construit grâce à :</h2>
            <h3 class="legale"><a href="https://www.djangoproject.com/">Django</a></h3>
            <h3 class="legale"><a href="https://getbootstrap.com/">Bootstrap</a></h3>

            <h2 class="pt-4 legale">Ce site est hebergé par : </h2>
            <h3 class="legale"><a href="https://www.heroku.com/">Heroku</a></h3>
        </div>

        <div class="col-0 col-md-3"></div>

    </div>

</section>
{% endblock %}

home/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block header %}

<header class="masthead" style="background-image: none; background-color: #5c4d42;">
    {% block header_content %}
    {% if form.errors %}
        <p style="color: red">Votre nom d’utilisateur et votre mot de passe ne correspondent pas. Veuillez réessayer.</p>
    {% endif %}
    <h2>Connectez-vous à mon site</h2>
    <form method="post">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}" />
        {% for field in form %}
            <p>
                {{ field.label_tag }}<br>
                {{ field }}<br>
                {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                {% endfor %}
                {% if field.help_text %}
                    <p><small style="color: grey">{{ field.help_text }}</small></p>
                {% endif %}
            </p>
        {% endfor %}
        <button type="submit" id="button-submit">Se connecter</button>
        <p><a href="{% url 'signup' %}">Nouveau sur le site? Inscrivez-vous</a></p>
        <p><a id="button-passcode" href="{% url 'password_reset' %}">Mot de passe oublié? Réinitialisez votre mot de passe</a></p>
    </form>
    {% endblock %}
</header>

{% endblock %}

home/templates/product_info.html
{% extends 'base.html' %}

{% block header %}

<header class="product-head">
    <img src="{{ product.image_url }}" alt="product recherché" class="product-image">
    <h1 class="product-head-title">
    <a href="{{ product.url }}">{{ product.product_name }}</a>
    </h1>
</header> 

{% endblock %}

{% block content %}
    <div class="container">
        <div class="row mt-5">
            <div class="col-6 d-flex justify-content-center align-items-center">
                <img src="https://static.openfoodfacts.org/images/misc/nutriscore-{{ product.nutrition_grade_fr }}.svg" alt="nutriscore" class="nutriscore-image">
            </div>
            <div class="col-6 d-flex justify-content-center align-items-center">
                <img src="{{ product.image_nutrition_url }}" alt="images nutritionnels" class="product-image-nutriscore" width="300">
            </div>
            <div class="col-12 d-flex justify-content-center align-items-center m-5"><a href="{{ product.url }}" class="lien-url">Voir la fiche d'openfoodfacts</a></div>
        </div>
    </div>
{% endblock %}

home/templates/research.html
{% extends 'base.html' %}
{% load static %}


{% block header %}
{% if product %}

<header class="product-head">
    <img src="{{ product.image_url }}" alt="product recherché" class="product-image">

    <h1 class="product-head-title"><a  href="{{ product.url }}">{{ product.product_name }}</a></h1>

</header> 

{% else %}

<header class="masthead">

    <div class="header-container"> 
    <h1>Du gras oui, mais de qualité!</h1>
    <hr>
    <h2>Trouvez un produit de substitution pour ceux que vous consommez tous les jours.</h2>

    <form action="{% url 'research' %}" method="get" class="header-form">
        {% csrf_token %}
        <input type="text" id="product-input" name="product" class="form-control product-input">
        <p><button type="submit">Rechercher</button></p>
    </form>
    

    {% if envoi %}
        <p>Vois-ci votre résultat: </p>
    {% endif %}
    </div>

</header>

{% endif %}
{% endblock %}

{% block content %}
    <div class="product-result container">
        {% if product %}
        <p class="row"><h3>Vous pouvez remplacer cet aliment par:</h3></p>
        {% endif %}
        <div class="row">
{% for substitute in substitutes %}
            <div class="col-md-4 result">
                <div class="result-image-nutriscore">
                    <img src="{{ substitute.image_url }}" width="100" height="100" class="result-image">
                    <div class="result-nutriscore result-nutriscore-{{ substitute.nutrition_grade_fr }}">{{ substitute.nutrition_grade_fr }}</div>
                </div>
                <a class="result-name" href="{% url 'product_info' substitute.code %}">{{ substitute.product_name }}</a>
                {% if user.is_authenticated %}
                <form class="result-form" method="post" action="{% url 'favorite_save' %}">
                    {% csrf_token %}
                    <input type="hidden" name="product-code" value="{{ product.code }}">
                    <input type="hidden" name="substitute-code" value="{{ substitute.code }}">
                    <button class="result-button" type="submit">Sauvegarder</button>
                </form>
                {% endif %}
            </div>
{% empty %}
            <div class="product-noresult col-md-6 offset-md-3"><center>Désolé, aucun produit n'a été trouvé</center></div>
{% endfor %}
        </div>
    </div>  

{% endblock %}

home/templates/signup.html
{% extends 'base.html' %}

{% block header %}

<header class="masthead" style="background-color: orange; background-image: none;">
    {% block header_content %}
    <form method="post">
        {% csrf_token %}
        {% for field in signup_form %}
            <p>
                {{ field.label_tag }}<br>
                {{ field }}
                {% if field.help_text %}
                    <small style="color: grey">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                {% endfor %}
            </p>
        {% endfor %}
        <button type="submit">s'enregistrer</button>
    </form>
    {% endblock %}
</header>

{% endblock %}